spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://34.72.94.112:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ${jdbcpassword}
    hikari:
      connection-timeout: 30000
      minimum-idle: 20
      maximum-pool-size: 300
      max-lifetime: 1800000
  liquibase:
    enabled: true
    contexts: prod
    parameters:
      textColumnType: TEXT
