spring:
  datasource:
    url: jdbc:h2:file:~/embedded-db;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2.console.enabled: true
  liquibase:
    enabled: true
    contexts: prod
    parameters:
      textColumnType: VARCHAR(250)
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
