spring:
  application:
    name: wow-server
  profiles:
    active: local
server:
  port: 8787

management:
  endpoints:
    web:
      exposure:
        include: health,configprops
  endpoint:
    health:
      show-details: always

springdoc:
  packagesToScan: com.wow.server.controller
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
