create table if not exists tb_user
(
	user_id bigint generated by default as identity
		constraint tb_user_pkey
			primary key,
	user_name text not null,
	display_name text not null,
	email text,
	password text,
	date_of_birth date,
	education_level text,
	first_trade_date date,
	have_child text,
	introduction text,
	marital_status text,
	monthly_income_range text,
	risk_profile integer,
	asset_size_range text,
	creation_date_time timestamp,
	update_date_time timestamp
);

alter table tb_user owner to postgres;

create table if not exists tb_product
(
	product_id bigint generated by default as identity
		constraint tb_product_pkey
			primary key,
	product_name text not null,
	product_code text not null,
	price numeric(19,2),
	revenue numeric(19,2),
	sector text,
	industry text,
	pe_ratio numeric(19,2),
	market_cap numeric(19,2),
	avg_dividend_yield numeric(19,2),
	avg_volume numeric(19,2),
	price_one_day_change numeric(19,2),
	total_cash numeric(19,2),
	total_devidend_yield numeric(19,2),
	creation_date_time timestamp,
	update_date_time timestamp
);

alter table tb_product owner to postgres;

create table if not exists tb_holding
(
	holding_id bigint generated by default as identity
		constraint tb_holding_pkey
			primary key,
	user_id bigint not null
		constraint fk_holding_user
			references tb_user,
	product_id bigint not null
		constraint fk_holding_product
			references tb_product,
	quantity numeric(19,4),
	avg_purchase_price numeric(19,2),
	creation_date_time timestamp,
	update_date_time timestamp
);

alter table tb_holding owner to postgres;

create table if not exists tb_watch_item
(
	watch_item_id bigint generated by default as identity
		constraint tb_watch_item_pkey
			primary key,
	user_id bigint not null
		constraint fk_watch_item_user
			references tb_user,
	product_id bigint not null
		constraint fk_watch_item_product
			references tb_product,
	creation_date_time timestamp,
	update_date_time timestamp
);

alter table tb_watch_item owner to postgres;

create table if not exists tb_follow
(
	follow_id bigint generated by default as identity
		constraint tb_follow_pkey
			primary key,
	user_id bigint not null
		constraint fk_follow_user
			references tb_user,
	follower_id bigint not null
		constraint fk_follow_follower
			references tb_user,
	creation_date_time timestamp,
	update_date_time timestamp
);

alter table tb_follow owner to postgres;

create table if not exists tb_order
(
	trade_id bigint generated by default as identity
		constraint tb_order_pkey
			primary key,
	user_id bigint not null,
	product_id bigint not null,
	quantity numeric(19,2),
	order_price numeric(19,4),
	order_status text,
	creation_date_time timestamp,
	update_date_time timestamp
);

alter table tb_order owner to postgres;

